export const NavigationList = [
  { href: '/', text: 'Main' },
  { href: '/about', text: 'About Us' },
  { href: '/forms', text: 'Forms' },
];

export const movies = [
  {
    Title: 'Game of Thrones',
    Year: '2011–2019',
    Rated: 'TV-MA',
    Released: '17 Apr 2011',
    Runtime: '57 min',
    Genre: 'Action, Adventure, Drama',
    Director: 'N/A',
    Writer: 'David Benioff, D.B. Weiss',
    Actors: 'Emilia Clarke, Peter Dinklage, Kit Harington',
    Plot: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    Language: 'English',
    Country: 'United States, United Kingdom',
    Awards: 'Won 59 Primetime Emmys. 387 wins & 632 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '9.2/10',
      },
    ],
    Metascore: 'N/A',
    imdbRating: '9.2',
    imdbVotes: '2,051,339',
    imdbID: 'tt0944947',
    Type: 'series',
    totalSeasons: '8',
    Response: 'True',
  },
  {
    Title: 'Duna',
    Year: '2021',
    Rated: 'N/A',
    Released: '25 May 2021',
    Runtime: '155 min',
    Genre: 'Drama',
    Director: 'Dany Campos',
    Writer: 'Dany Campos, Alba Esquinas, Alberto S. Regatos',
    Actors: 'Alvaro Cañaveras, Fernando Cornejo, Xabier Fonseca',
    Plot: 'Victoria is about to present an ambitious professional project to investors when her twin sister Duna disappears. Victoria must decide whether to dedicate all her efforts to find her, despite putting her project at risk.',
    Language: 'Spanish',
    Country: 'Spain',
    Awards: 'N/A',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDA5ZTZlMGQtNTMyMS00MzE5LTlmNTMtZDg5NTFiYzU3ZTUyXkEyXkFqcGdeQXVyNTMyNzc1MjA@._V1_SX300.jpg',
    Ratings: [],
    Metascore: 'N/A',
    imdbRating: 'N/A',
    imdbVotes: '9',
    imdbID: 'tt13624526',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Interstellar',
    Year: '2014',
    Rated: 'PG-13',
    Released: '07 Nov 2014',
    Runtime: '169 min',
    Genre: 'Adventure, Drama, Sci-Fi',
    Director: 'Christopher Nolan',
    Writer: 'Jonathan Nolan, Christopher Nolan',
    Actors: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Language: 'English',
    Country: 'United States, United Kingdom, Canada',
    Awards: 'Won 1 Oscar. 44 wins & 148 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '8.6/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '73%',
      },
      {
        Source: 'Metacritic',
        Value: '74/100',
      },
    ],
    Metascore: '74',
    imdbRating: '8.6',
    imdbVotes: '1,788,073',
    imdbID: 'tt0816692',
    Type: 'movie',
    DVD: '31 Mar 2015',
    BoxOffice: '$188,020,017',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'The Day After Tomorrow',
    Year: '2004',
    Rated: 'PG-13',
    Released: '28 May 2004',
    Runtime: '124 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Roland Emmerich',
    Writer: 'Roland Emmerich, Jeffrey Nachmanoff',
    Actors: 'Dennis Quaid, Jake Gyllenhaal, Emmy Rossum',
    Plot: 'Jack Hall, paleoclimatologist, must make a daring trek from Washington, D.C. to New York City to reach his son, trapped in the cross-hairs of a sudden international storm which plunges the planet into a new Ice Age.',
    Language: 'English, Japanese, French, Arabic',
    Country: 'United States',
    Awards: 'Won 1 BAFTA Award6 wins & 12 nominations total',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNWNkNzljZjktY2MwNi00OWExLTliNTMtOTk0NGU2ZDQ3ZTEyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Ratings: [
      {
        Source: 'Internet Movie Database',
        Value: '6.4/10',
      },
      {
        Source: 'Rotten Tomatoes',
        Value: '45%',
      },
      {
        Source: 'Metacritic',
        Value: '47/100',
      },
    ],
    Metascore: '47',
    imdbRating: '6.4',
    imdbVotes: '447,049',
    imdbID: 'tt0319262',
    Type: 'movie',
    DVD: '12 Oct 2004',
    BoxOffice: '$186,740,799',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True',
  },
];
